'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class actividades
    Public Property id_actividad As Integer
    Public Property de_actividad As String
    Public Property duracion As Nullable(Of Integer)
    Public Property pr_actividad As Nullable(Of Decimal)
    Public Property sn_activo As String

    Public Overridable Property socios As ICollection(Of socios) = New HashSet(Of socios)
    Public Overridable Property entrenadores As ICollection(Of entrenadores) = New HashSet(Of entrenadores)

End Class
