'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class taller2Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=taller2Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property actividades() As DbSet(Of actividades)
    Public Overridable Property entrenadores() As DbSet(Of entrenadores)
    Public Overridable Property factura() As DbSet(Of factura)
    Public Overridable Property factura_detalle() As DbSet(Of factura_detalle)
    Public Overridable Property socios() As DbSet(Of socios)
    Public Overridable Property tipo_pago() As DbSet(Of tipo_pago)
    Public Overridable Property usuario() As DbSet(Of usuario)
    Public Overridable Property empresa() As DbSet(Of empresa)
    Public Overridable Property pagos() As DbSet(Of pagos)

    Public Overridable Function p_factura_detalle(fecha As Nullable(Of Date), id As Nullable(Of Integer)) As ObjectResult(Of p_factura_detalle_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of p_factura_detalle_Result)("p_factura_detalle", fechaParameter, idParameter)
    End Function

    Public Overridable Function sp_comprobante(fecha As Nullable(Of Date), id As Nullable(Of Integer)) As ObjectResult(Of sp_comprobante_Result)
        Dim fechaParameter As ObjectParameter = If(fecha.HasValue, New ObjectParameter("fecha", fecha), New ObjectParameter("fecha", GetType(Date)))

        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Integer)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of sp_comprobante_Result)("sp_comprobante", fechaParameter, idParameter)
    End Function

End Class
