'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class empresa
    Public Property id_empresa As Integer
    Public Property nombre As String
    Public Property direccion As String
    Public Property telefono As Nullable(Of Long)
    Public Property us_login As String
    Public Property us_pass As String
    Public Property id_cuit As String
    Public Property localidad As String
    Public Property provincia As String
    Public Property web As String
    Public Property email As String

End Class
