'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class entrenadores
    Public Property id_entrenador As Integer
    Public Property dni As Nullable(Of Integer)
    Public Property nombre As String
    Public Property apellido As String
    Public Property telefono As Nullable(Of Long)
    Public Property direccion As String
    Public Property email As String
    Public Property fe_nacimiento As Nullable(Of Date)
    Public Property sexo As String
    Public Property sn_activo As String

    Public Overridable Property actividades As ICollection(Of actividades) = New HashSet(Of actividades)

End Class
