'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class factura_detalle
    Public Property id_factura As Integer
    Public Property id_facturadetalle As Integer
    Public Property observacion As String
    Public Property descuento As Nullable(Of Decimal)
    Public Property id_actividades As Nullable(Of Integer)

    Public Overridable Property factura As factura

End Class
