'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class factura
    Public Property id_factura As Integer
    Public Property id_socio As Nullable(Of Integer)
    Public Property fe_factura As Nullable(Of Date)
    Public Property fe_vencimiento As Nullable(Of Date)
    Public Property id_tipo As Nullable(Of Integer)
    Public Property monto As Nullable(Of Decimal)

    Public Overridable Property socios As socios
    Public Overridable Property tipo_pago As tipo_pago
    Public Overridable Property factura_detalle As ICollection(Of factura_detalle) = New HashSet(Of factura_detalle)

End Class
