'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class pagos
    Public Property id_factura As Integer
    Public Property apellido As String
    Public Property nombre As String
    Public Property importe As Nullable(Of Decimal)
    Public Property fe_factura As Nullable(Of Date)
    Public Property fe_vencimiento As Nullable(Of Date)
    Public Property descripcion As String
    Public Property dni As Nullable(Of Integer)

End Class
