'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tipo_pago
    Public Property id_tipo As Integer
    Public Property descripcion As String

    Public Overridable Property factura As ICollection(Of factura) = New HashSet(Of factura)

End Class
