'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class usuario
    Public Property id_usuario As Integer
    Public Property us_login As String
    Public Property us_pass As String
    Public Property us_tipo As String
    Public Property us_descrip As String
    Public Property dni As Nullable(Of Long)
    Public Property apellido As String
    Public Property nombre As String
    Public Property telefono As String
    Public Property direccion As String
    Public Property email As String
    Public Property sn_activo As String

End Class
